import SessionProviders from "@/components/Providers/SessionProvider";
import "./globals.css";
import { Inter, Kumbh_Sans } from "next/font/google";
import NextThemeProvider from "@/components/Providers/NextThemeProvider";
import ToasterContext from "@/components/Providers/ToasterContext";
import ReduxProvider from "@/components/Providers/ReduxProvider";
import RtkProvider from "@/components/Providers/RtkProvider";

const kumbh_sans = Kumbh_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Dev Jobs",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={kumbh_sans.className}>
        <ReduxProvider>
        <SessionProviders>
          <NextThemeProvider>
            <RtkProvider>
            <ToasterContext />
            {children}
            </RtkProvider>
            </NextThemeProvider>
        </SessionProviders>
        </ReduxProvider>
        <div id="root-modal"></div>
      </body>
    </html>
  );
}
